### PR TITLE
Add DynamicPrompts with examples inspired by Promptagator

### PR DESCRIPTION
**Pull request by m-krastev**
Add DynamicPrompts with examples inspired by Promptagator's prompt design. 
In addition, speed up prompt creation 3x with multiple processes (60s -> 20s [Scifact])

### CODE REVIEW

**Review by MJHamar — APPROVED** [review]
makes a lot of sense

**Comment by danilotpnta** [comment]
What is the #magic number 30 in the qlen at prompt.py. Is it related to max_new_gen tokens for the query?

**Comment by m-krastev** [comment]
> What is the #magic number 30 in the qlen at prompt.py. Is it related to max_new_gen tokens for the query?

It's an adjusted average length of the query. We can potentially replace it with `max_new_gen`

**Comment by danilotpnta** [comment]
Approved! 
I have seen some paper that use 25 and also ensure that the generated response is clean ie no more strings after ‘?’ Page 4
 https://dl.acm.org/doi/pdf/10.1145/3616855.3635856
 @JesseBrouw

**Pull request merged**
