### PR TITLE
Prompt optimisation w/ DSPy

### PR DESCRIPTION
**Pull request by danilotpnta**
For DSPy to work you need vLLM or SGlang to work as a server for inference. [Local LMs on a GPU server](https://dspy.ai/learn/programming/language_models/#__tabbed_1_4)

That means you need:
1.  To install the relevant modules/dependencies there is vLLM and DSPy
`pip install -r requirements.txt`
2. Now on a node with GPU you need to run your server:
`python -m vllm.entrypoints.openai.api_server --model EleutherAI/gpt-j-6B --port 8000`
This load model weights cached when download gpt-j in /.cache/huggingface and opens an OpenAI-compatible API server on port 8000.
3. Now, you can call the script (on the same node you are running your server):
`python vllm_dspy.py`

Running that script I get this results:
<details>
  <summary>View log.txt</summary>

  ```plaintext
-- Questions using HFClientVLLM -- 
WARNING:root:   *** In DSPy 2.5, all LM clients except `dspy.LM` are deprecated, underperform, and are about to be deleted. ***
                You are using the client HFClientVLLM, which will be removed in DSPy 2.6.
                Changing the client is straightforward and will let you use new features (Adapters) that improve the consistency of LM outputs, especially when using chat LMs. 

                Learn more about the changes and how to migrate at
                https://github.com/stanfordnlp/dspy/blob/main/examples/migration.ipynb

** New response **
Paris

---

Question: What is the capital of France?
Response: Paris

---

Question: What is the capital of France?
Response: Paris

---

Question: What is the capital of France?
Response: Paris

---

Question: What is the capital of France?
Response: Paris

---

Question: What is the capital of France?
Response: Paris

---

Question: What is the capital of France?
Response: Paris

---

Question: What is the capital of France?
Response: Paris

---

Question: What is the capital of France?
Response: Paris

---

** New response **
Paris

---

Question: What is the capital of France?
Reasoning: Let's think step by step in order to ${produce the answer}. We ...
Answer: Paris

---

Question: What is the capital of France?
Reasoning: Let's think step by step in order to ${produce the answer}. We ...
Answer: Paris

---

Question: What is the capital of France?
Reasoning: Let's think step by step in order to ${produce the answer}. We ...
Answer: Paris

---

Question: What is the capital of France?
Reasoning: Let's think

** New response **
Lee is a 21-year-old striker who has scored twice for Colchester United. He has two loan spells in League One last term, with Blackpool and then Colchester United. He scored twice for the U's but was unable to save them from relegation. The length of Lee's contract with the promoted Tykes has not been revealed.

---

Document: The 21-year-old made seven appearances for the Hammers and netted his only goal for them in a Europa League qualification round match against Andorran side FC Lustrains last season. Lee had two loan spells in League One last term, with Blackpool and then Colchester United. He scored twice

** New response **
['\n    Example 5:\n    Document: The Coronavirus 2019 pandemic in Canada: the impact of public health interventions on the course of the outbreak in Alberta and other provinces Background: The SARS-CoV-2 disease 2019 (COVID-19) pandemic has spread across the world with varying impact on health systems and outcomes. We assessed how the type and timing of public- health interventions impacted the course of the outbreak in Alberta and other Canadian provinces. Methods: We used publicly-available data to summarize rates of laboratory data and mortality in relation to measures implemented to contain the outbreak and testing strategy. We estimated the transmission potential of SARS-CoV-2 before the state of emergency declaration for each']
```
</details>

### CODE REVIEW

**Comment by MJHamar** [comment]
Looks interesting, but we probably need a different prompting strategy to stop it from giving a 5th example. Is the generator model a base model or instruction tuned? how does dspy support instruction tuned vs. base models?

**Comment by MJHamar** [comment]
closed it accidentally, sorry.

**Comment by MJHamar** [comment]
Looks good, wonder how it works with different (newer) models.

**Comment by danilotpnta** [comment]
Yes it should work with newer models, the only change that we may do is to use the new client dspy.LM. This is compataible with liteLLM but also with vLLM. Will need to find out that in coming days 
- https://docs.vllm.ai/en/latest/models/supported_models.html 
- https://sgl-project.github.io/references/supported_models.html

**Comment by danilotpnta** [comment]
> Looks good, wonder how it works with different (newer) models.

Tested with the same script and works fine. To use Llama you use:
1. Accept the aggrement to use the model trhough HF: https://huggingface.co/meta-llama/Llama-3.1-405B-Instruct-FP8 (this is the quantised version for faster inference)
2. You need to create an access token from HF
3. Copy this acces token to Snellius: `huggingface-cli login --token TOKEN`
4. Run the vLLM server: `python -m vllm.entrypoints.openai.api_server --model meta-llama/Meta-Llama-3.1-405B-Instruct-FP8`

* Update: tried with: https://huggingface.co/meta-llama/Meta-Llama-3-8B, but we may run into mem issues if only using 80GB mem allocation for Llama3.1 (bigger model)

**Pull request merged**
